services:
  valentin:
    build: .
    container_name: ValentinMusic
    restart: unless-stopped
    volumes:
      - ./cache:/app/cache
      - ./downloads:/app/downloads
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
