[project]
name = "ValentinMusic"
version = "3.0.3"
description = "Telegram Group Calls Streaming Bot with YouTube support."
readme = ".github/README.md"
requires-python = ">=3.10"

dependencies = [
    "aiofiles",
    "aiohttp",
    "beautifulsoup4",
    "dnspython",
    "gitpython",
    "gTTS",
    "hachoir",
    "httpx",
    "pyrofork",
    "motor",
    "pillow",
    "psutil",
    "py-tgcalls>=2.2.0",
    "py-yt-search",
    "pykeyboard",
    "pymongo",
    "pysocks",
    "python-dotenv",
    "pytz",
    "pyyaml",
    "requests",
    "speedtest-cli",
    "telethon",
    "unidecode",
    "youtube-search",
    "youtube-search-python",
    "yt-dlp[default]",
]
